{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "self = <pytest_demo.test_allure.TestAllure object at 0x10f829ef0>\n\n    @allure.story(\"测试中断\")\n    def test_broken(self):\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_allure.py:24: Exception"}, "start": 1594115079639, "stop": 1594115079639, "uuid": "487ad7b6-80b9-4023-9a11-a9c4efadef9a", "historyId": "febd111dbbcdb4022d301a2ef7720c2d", "testCaseId": "c46d6a8dd3d38f879fe4d1cb1684a04e", "fullName": "test_allure.TestAllure#test_broken", "labels": [{"name": "feature", "value": "测试样例"}, {"name": "story", "value": "测试中断"}, {"name": "suite", "value": "test_allure"}, {"name": "subSuite", "value": "TestAllure"}, {"name": "host", "value": "heweimaodeMacBook-Pro.local"}, {"name": "thread", "value": "61586-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}